function SInput=patch_008_perf_testing_update_params(~,SInput)
SInput.performanceTestingParams.samplesMeshModeName='uniform';
SInput.performanceTestingParams.samplesMeshModeProps=...
    struct(...
    'uniform',{struct(...
    'minNumOfTuples',SInput.performanceTestingParams.minNumOfTuples,...
    'maxNumOfTuples',SInput.performanceTestingParams.maxNumOfTuples,...
    'nTuplesSamples',SInput.performanceTestingParams.nTuplesSamples)},...
    'manual',{struct(...
    'nTuplesVec',{nan(1,0)})});
nTrialsPerSample=SInput.performanceTestingParams.nTrialsPerSample;
SInput.performanceTestingParams=rmfield(SInput.performanceTestingParams,...
    {'minNumOfTuples','maxNumOfTuples',...
    'nTuplesSamples','nTrialsPerSample'});
SInput.performanceTestingParams.nTrialsPerSample=nTrialsPerSample;
